<h2>TEXTO: <?php echo $this->flag; ?></h2>

<p>
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam quis vulputate neque. Curabitur at urna eu mi accumsan varius eget non ligula. In ornare et velit eget tristique. Nullam dictum pulvinar massa nec vestibulum. Etiam id tempus sem, eu interdum sapien. Nulla bibendum arcu quis ex aliquam viverra. Cras et mauris nisl. Quisque imperdiet diam nibh, dictum placerat tellus bibendum placerat. Aenean mi dolor, accumsan eget enim iaculis, congue tincidunt tellus. Nullam sollicitudin arcu ac mauris venenatis, nec vehicula lorem mattis.
</p>
