<h2>AZUL: <?php echo $this->flag; ?></h2>

<p style="color:white; background-color:blue;">
Etiam porttitor dolor vitae erat tempus, vel finibus risus mattis. Ut dictum efficitur mi eget volutpat. Praesent felis nulla, lacinia eu turpis ut, dignissim luctus lorem. Nam at diam eu sem euismod ornare in quis orci. Phasellus elementum, erat dapibus venenatis placerat, elit nunc dapibus orci, et convallis metus neque eget urna. In hac habitasse platea dictumst. Nullam tempor sem augue, quis posuere risus imperdiet eget. Maecenas quis sapien porttitor, aliquam enim at, venenatis ante. Ut a aliquet nibh.
</p>
